version: '3'

services:
  # DataStax Enterprise
  dse-server:
    image: datastax/dse-server
    command: [ -s ]
    ports:
    - "9042:9042" # cassandra
    environment:
      DS_LICENSE: accept
    volumes:
    - "./data:/var/lib/cassandra"
    # Allow DSE to lock memory with mlock
    cap_add:
    - IPC_LOCK
    ulimits:
      memlock: -1

# One instance of DataStax Studio
  dse-studio:
    image: datastax/dse-studio
    ports:
    # The Web UI exposed to our host
    - "9091:9091"
    depends_on:
    - dse-server
    environment:
      DS_LICENSE: accept
    volumes:
    - "./notebooks:/var/lib/datastax-studio"